// Public-domain Ethiopian Orthodox / Pseudepigrapha texts.
// Bundled JSON, generated by scripts/fetch-extra-books.ts.
//
// IDs use the prefix "extra:" so we can route around api.bible.

import type { Bible, Book as ApiBook, Chapter as ApiChapter, Passage } from "./bible-api";
import enoch from "@/data/extra-books/enoch.json";
import jubilees from "@/data/extra-books/jubilees.json";

type RawBook = {
  id: string;
  name: string;
  abbreviation: string;
  description: string;
  source: string;
  translator: string;
  year: string;
  chapters: { number: string; verses: { number: string; text: string }[] }[];
};

const BOOKS: RawBook[] = [enoch as RawBook, jubilees as RawBook];

const ID_PREFIX = "extra-";

export function isExtraBibleId(id: string): boolean {
  return id.startsWith(ID_PREFIX);
}

export function listExtraBibles(): Bible[] {
  return BOOKS.map((b) => ({
    id: `${ID_PREFIX}${b.id}`,
    name: `${b.name} (${b.translator}, ${b.year})`,
    nameLocal: b.name,
    abbreviation: b.abbreviation,
    abbreviationLocal: b.abbreviation,
    description: `${b.description} — public domain ${b.translator} translation, ${b.year}.`,
    language: { id: "eng", name: "English", nameLocal: "English" },
  }));
}

function findBook(bibleId: string): RawBook | null {
  const stripped = bibleId.replace(ID_PREFIX, "");
  return BOOKS.find((b) => b.id === stripped) ?? null;
}

export function listExtraBooks(bibleId: string): ApiBook[] {
  const b = findBook(bibleId);
  if (!b) return [];
  // We model each "Bible" as containing a single Book — the work itself.
  // Chapters live under that one book.
  return [
    {
      id: b.id,
      bibleId: bibleId,
      name: b.name,
      nameLong: b.name,
      abbreviation: b.abbreviation,
    },
  ];
}

export function listExtraChapters(bibleId: string): ApiChapter[] {
  const b = findBook(bibleId);
  if (!b) return [];
  return b.chapters.map((c) => ({
    id: `${b.id}.${c.number}`,
    bibleId,
    bookId: b.id,
    number: c.number,
    reference: `${b.name} ${c.number}`,
  }));
}

// passageId format: "<book-id>.<chapter>"  e.g. "enoch.charles1917.6"
export function getExtraPassage(bibleId: string, passageId: string): Passage | null {
  const b = findBook(bibleId);
  if (!b) return null;
  const chapterNum = passageId.split(".").pop() ?? "1";
  const ch = b.chapters.find((c) => c.number === chapterNum);
  if (!ch) return null;

  // Build content with verse markers in api.bible style: "[1] text [2] text..."
  // — keeps the companion prompt's verse-detection happy.
  const content = ch.verses
    .map((v) => `[${v.number}] ${v.text}`)
    .join(" ");

  return {
    id: passageId,
    bibleId,
    reference: `${b.name} ${chapterNum}`,
    content,
    verseCount: ch.verses.length,
    copyright: `Public domain — ${b.translator} ${b.year}`,
  };
}

export function chaptersFor(bibleId: string): { number: string; count: number } | null {
  const b = findBook(bibleId);
  if (!b) return null;
  return {
    number: b.chapters.length.toString(),
    count: b.chapters.length,
  };
}
