// Full multi-book public-domain Bibles bundled with the app (not on api.bible).
// Generated by scripts/fetch-1812-bible.ts into data/local-bibles/<id>.json.
//
// Unlike the single-work "extra-books" path (Enoch, Jubilees), these are full
// canonical Bibles and surface as ordinary versions in the language picker.
//
// IDs use the prefix "local-" so bible-api.ts can route around api.bible.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import type {
  Bible,
  Book as ApiBook,
  Chapter as ApiChapter,
  Passage,
} from "./bible-api";

type RawVerse = { number: string; text: string };
type RawChapter = { number: string; verses: RawVerse[] };
type RawBook = {
  id: string;
  name: string;
  abbreviation: string;
  chapters: RawChapter[];
};
type LocalBible = {
  id: string;
  name: string;
  abbreviation: string;
  language: { id: string; name: string; nameLocal: string };
  copyright: string;
  books: RawBook[];
};

const ID_PREFIX = "local-";

// Files live under data/local-bibles/. Loaded from disk once, then cached —
// the app runs as a long-lived Node server (Railway), so this stays in memory.
const FILES = ["1812-kjva.json"];

let cache: LocalBible[] | null = null;

function load(): LocalBible[] {
  if (cache) return cache;
  const dir = join(process.cwd(), "data", "local-bibles");
  cache = FILES.map(
    (f) => JSON.parse(readFileSync(join(dir, f), "utf8")) as LocalBible,
  );
  return cache;
}

export function isLocalBibleId(id: string): boolean {
  return id.startsWith(ID_PREFIX);
}

function findBible(bibleId: string): LocalBible | null {
  const stripped = bibleId.replace(ID_PREFIX, "");
  return load().find((b) => b.id === stripped) ?? null;
}

export function listLocalBibles(): Bible[] {
  return load().map((b) => ({
    id: `${ID_PREFIX}${b.id}`,
    name: b.name,
    nameLocal: b.name,
    abbreviation: b.abbreviation,
    abbreviationLocal: b.abbreviation,
    description: b.copyright,
    language: b.language,
  }));
}

export function listLocalBooks(bibleId: string): ApiBook[] {
  const b = findBible(bibleId);
  if (!b) return [];
  return b.books.map((bk) => ({
    id: bk.id,
    bibleId,
    name: bk.name,
    nameLong: bk.name,
    abbreviation: bk.abbreviation,
  }));
}

export function listLocalChapters(bibleId: string, bookId: string): ApiChapter[] {
  const b = findBible(bibleId);
  if (!b) return [];
  const book = b.books.find((bk) => bk.id === bookId);
  if (!book) return [];
  return book.chapters.map((c) => ({
    id: `${book.id}.${c.number}`,
    bibleId,
    bookId: book.id,
    number: c.number,
    reference: `${book.name} ${c.number}`,
  }));
}

// passageId format: "<book-id>.<chapter>"  e.g. "GEN.1"
export function getLocalPassage(bibleId: string, passageId: string): Passage | null {
  const b = findBible(bibleId);
  if (!b) return null;
  const [bookId, chapterNum] = passageId.split(".");
  const book = b.books.find((bk) => bk.id === bookId);
  if (!book) return null;
  const ch = book.chapters.find((c) => c.number === chapterNum);
  if (!ch) return null;

  // api.bible-style inline verse markers: "[1] text [2] text..." — keeps the
  // companion / annotation prompts' verse-detection happy.
  const content = ch.verses.map((v) => `[${v.number}] ${v.text}`).join(" ");

  return {
    id: passageId,
    bibleId,
    reference: `${book.name} ${chapterNum}`,
    content,
    verseCount: ch.verses.length,
    copyright: b.copyright,
  };
}
