// Full multi-book public-domain canons bundled with the app, surfaced as normal
// English versions (unlike lib/extra-books.ts, which models single-work
// pseudepigrapha). IDs use the prefix "local-" so we can route around api.bible.
//
// Bundled JSON is generated by scripts/fetch-1812-bible.ts.

import type { Bible, Book as ApiBook, Chapter as ApiChapter, Passage } from "./bible-api";
import kjva1812 from "@/data/local-bibles/1812-kjva.json";

interface RawVerse {
  number: string;
  text: string;
}
interface RawChapter {
  number: string;
  verses: RawVerse[];
}
interface RawBook {
  id: string;
  name: string;
  abbreviation: string;
  chapters: RawChapter[];
}
interface RawBible {
  id: string;
  name: string;
  abbreviation: string;
  description: string;
  source: string;
  license: string;
  language: string;
  books: RawBook[];
}

const BIBLES: RawBible[] = [kjva1812 as RawBible];

const ID_PREFIX = "local-";

export function isLocalBibleId(id: string): boolean {
  return id.startsWith(ID_PREFIX);
}

function findBible(bibleId: string): RawBible | null {
  const stripped = bibleId.replace(ID_PREFIX, "");
  return BIBLES.find((b) => b.id === stripped) ?? null;
}

export function listLocalBibles(): Bible[] {
  return BIBLES.map((b) => ({
    id: `${ID_PREFIX}${b.id}`,
    name: b.name,
    nameLocal: b.name,
    abbreviation: b.abbreviation,
    abbreviationLocal: b.abbreviation,
    description: `${b.description} — ${b.license}.`,
    language: { id: "eng", name: "English", nameLocal: "English" },
  }));
}

export function listLocalBooks(bibleId: string): ApiBook[] {
  const b = findBible(bibleId);
  if (!b) return [];
  return b.books.map((book) => ({
    id: book.id,
    bibleId,
    name: book.name,
    nameLong: book.name,
    abbreviation: book.abbreviation,
  }));
}

export function listLocalChapters(bibleId: string, bookId: string): ApiChapter[] {
  const b = findBible(bibleId);
  if (!b) return [];
  const book = b.books.find((bk) => bk.id === bookId);
  if (!book) return [];
  return book.chapters.map((c) => ({
    id: `${book.id}.${c.number}`,
    bibleId,
    bookId: book.id,
    number: c.number,
    reference: `${book.name} ${c.number}`,
  }));
}

// passageId format: "<book-id>.<chapter>"  e.g. "GEN.1", "1CO.13"
export function getLocalPassage(bibleId: string, passageId: string): Passage | null {
  const b = findBible(bibleId);
  if (!b) return null;
  const parts = passageId.split(".");
  const chapterNum = parts.pop() ?? "1";
  const bookId = parts.join(".");
  const book = b.books.find((bk) => bk.id === bookId);
  if (!book) return null;
  const ch = book.chapters.find((c) => c.number === chapterNum);
  if (!ch) return null;

  // api.bible-style inline verse markers ("[1] text [2] text…") so the
  // companion/annotate prompts' verse detection keeps working.
  const content = ch.verses.map((v) => `[${v.number}] ${v.text}`).join(" ");

  return {
    id: passageId,
    bibleId,
    reference: `${book.name} ${chapterNum}`,
    content,
    verseCount: ch.verses.length,
    copyright: b.license,
  };
}
